CREATE TABLE `book_room2` (
  `id` int(10) NOT NULL,
  `name_hotel` varchar(255)  NULL COMMENT 'ชื่อโรมแรม',
  `details` varchar(255)  NULL,
  `province` varchar(255)  NULL COMMENT 'จังหวัด',
  `country` varchar(255)  NULL COMMENT 'ประเทศ',
  `name_image_hotel` varchar(255)  NULL,
  `image_hotel` longblob  NULL,
  
  `room_size1` varchar(255)  NULL COMMENT 'ขนาดห้อง',
  `details_room1` varchar(255)  NULL COMMENT 'detailsห้อง',
  `view_rooml` varchar(255)  NULL COMMENT '  วิวห้องพัก',
  `price1` varchar(255)  NULL COMMENT 'ราคา',
  `quantity1` int(255) NULL COMMENT 'ความจุห้อง',
  `Number_of_rooms1` int(11)  NULL COMMENT 'จำนวนห้องพัก',
  `Total1` int(11)  NULL COMMENT 'จำนวนห้องทั้งหมด',
  `image_room1_1` longblob  NULL,
  `image_room1_2` longblob  NULL,
  `image_room1_3` longblob  NULL,

  `room_size2` varchar(255)  NULL COMMENT 'ขนาดห้อง',
  `details_room2` varchar(255)  NULL COMMENT 'detailsห้อง',
  `view_room2` varchar(255)  NULL COMMENT '  วิวห้องพัก',
  `price2` varchar(255)  NULL COMMENT 'ราคา',
  `quantity2` int(255) NULL COMMENT 'ความจุห้อง',
  `Number_of_rooms2` int(11)  NULL COMMENT 'จำนวนห้องพัก',
  `Total2` int(11)  NULL COMMENT 'จำนวนห้องทั้งหมด',
  `image_room2_1` longblob  NULL,
  `image_room2_2` longblob  NULL,
  `image_room2_3` longblob  NULL,

  `room_size3` varchar(255)  NULL COMMENT 'ขนาดห้อง',
  `details_room3` varchar(255)  NULL COMMENT 'detailsห้อง',
  `view_room3` varchar(255)  NULL COMMENT '  วิวห้องพัก',
  `price3` varchar(255)  NULL COMMENT 'ราคา',
  `quantity3` int(255) NULL COMMENT 'ความจุห้อง',
  `Number_of_rooms3` int(11)  NULL COMMENT 'จำนวนห้องพัก',
  `Total3` int(11)  NULL COMMENT 'จำนวนห้องทั้งหมด',
  `image_room3_1` longblob  NULL,
  `image_room3_2` longblob  NULL,
  `image_room3_3` longblob  NULL,
  
  `status` varchar(255)  NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;